### ISSUE TITLE
Single responsibility per checker

### ISSUE THREAD

**Issue by adeneys** [JakobChristensen/Sitecore.Pathfinder#1]
Currently each checker checks for multiple conditions. For example, the `TemplateChecker` checks the templates name, short help text, long help text, Icon, etc. Ideally users should be allowed to disable any of the specific "rules" that the checkers check for. To do that, each individual rule will need to be in it's own class, identifiable by it's own "code" or ID.

This task would only cover splitting each rule out to it's own checker. Adding codes or ID or disabling them will be a separate issue.

**Comment by adeneys** [comment]
I will implement this task and submit a PR for it.

**Comment by JakobChristensen** [comment]
Good idea.

I completely agree with the "code" or ID and a category for more general control.

Anxiously awaiting the first pull request.

**Comment by JakobChristensen** [comment]
Done.
