### ISSUE TITLE
Allow execution without a project file

### ISSUE THREAD

**Issue by adeneys** [JakobChristensen/Sitecore.Pathfinder#2]
Should the compiler (`scc`) behave more like a language compiler such as the C# compiler (`csc`). Currently `scc` requires a project file to run. But it could just as easily run by passing the list of items as parameters to the executable. For example:

    scc master\** core\**

This would result in splitting the compiler portion from the build system, just like `csc` is split from MSBuild.

**Comment by JakobChristensen** [comment]
That would be cool.

I am not sure what the default behavior should be, but it should be easy to configure in the global scconfig.json.

I am thinking:
check-project
write-exports
pack-project

with some sensible defaults for config.

**Comment by JakobChristensen** [comment]
You can now build a project without a scconfig file. It will only generate a Nuget package.

It uses a default scconfig.json and sitecore.nuspec file in the [Tools]\files\project.noconfig folder.

If you execute scc.exe in the root of a Sitecore website, it will generate a package that excludes most Sitecore files in about 7 seconds.

I think this approach is acceptable and will close the issue.
