### ISSUE TITLE
Running scc is slow for development purposes

### ISSUE THREAD

**Issue by MartinSvarrer** [JakobChristensen/Sitecore.Pathfinder#24]
Running SCC for the sample TodoMvc application takes between 16 seconds and 22 seconds (first time 8 seconds).

That is simply too slow for a frontend developer to be usable during development. Maybe the workflow is not supposed to be used for frontend developers? The alternative for a frontend developer is copying the 1 edited file with a task runnner like Gulp, taking around 2 ms.

You want to get instant feedback while developing - otherwise each save becomes a drag and a source for loosing focus and checking facebook.

**Comment by JakobChristensen** [comment]
Hmm.. Takes under 2 seconds on my machine...

How big is your Nuget package?

Alternatively try using the install-project instead of the copy-package/install-package tasks.

**Comment by JakobChristensen** [comment]
Thought some more about this. I agree that Pathfinder absolutely needs to be fast to be useful. 

I think there is something odd about your scenario. It makes no sense that subsequent runs are slower than the first. 

If you only have files and no items in your solution, Pathfinder should be just as fast as Gulp (assuming Gulp also produces a Nuget package). Inserting items into the database naturally takes longer.

Which step takes up the majority of time? I have seen publishing take a long time for some reason.

**Comment by JakobChristensen** [comment]
Debugged this on Martin's machine - turned out it was caused by issue #25.
