### ISSUE TITLE
SCC crashing with new T4 template dll

### ISSUE THREAD

**Issue by Hafeok** [JakobChristensen/Sitecore.Pathfinder#4]
Im getting this error message, when trying to start the downloadable.

Do i need something more for the T4 templates to be loaded?

<pre> Program: scc.exe Framework-version: v4.0.30319 Beskrivelse: Denne proces blev afsluttet pga. en ubehandlet undtagelse. Undtagelsesoplysninger: System.IO.FileLoadException Stak: ved System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean) ved System.Reflection.RuntimeAssembly.nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean) ved System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean) ved System.Reflection.Assembly.Load(System.Reflection.AssemblyName) ved System.ComponentModel.Composition.Hosting.AssemblyCatalog.LoadAssembly(System.String) ved System.ComponentModel.Composition.Hosting.AssemblyCatalog..ctor(System.String) ved Sitecore.Pathfinder.Extensibility.StartupExtensions.AddFeatureAssemblies(System.Collections.Generic.ICollection`1<System.ComponentModel.Composition.Primitives.ComposablePartCatalog>, System.String) ved Sitecore.Pathfinder.Extensibility.StartupExtensions.RegisterCompositionService(Sitecore.Pathfinder.Startup, Microsoft.Framework.ConfigurationModel.IConfiguration, System.String, System.Reflection.Assembly, System.Collections.Generic.IEnumerable`1<System.String>, CompositionOptions) ved Sitecore.Pathfinder.Startup.Start() ved Sitecore.Pathfinder.Program.Main(System.String[]) </pre>

**Comment by JakobChristensen** [comment]
That is an odd one. Make sure that the follow files are in the same directory as scc.exe:
Mono.TextTemplating.dll
Unicorn.dll
Rainbow.dll
Rainbow.Storage.dll
Rainbow.Storage.Sc.dll

**Comment by Hafeok** [comment]
Ah its because the Unicorn and Rainbows dlls arent in the zip folder. 

do i need to get them my self or should it just work?

**Comment by JakobChristensen** [comment]
Ahh - you have an older build where you need to install unicorn. The files should be in the [Tools]/files/repository/sitecore.project/extensions/unicorn.zip

That has been fixed and unicorn is now installed by default.

**Comment by Hafeok** [comment]
Okay - i just downloaded the alpha version from the download link. 
But yeah the newest from the master branch works fine. 

A CI process for the zip package would be nice

**Comment by JakobChristensen** [comment]
I consider this issue closed.
