### ISSUE TITLE
Missing nuspec file in 0.67 alpha NuGet release

### ISSUE THREAD

**Issue by adeneys** [JakobChristensen/Sitecore.Pathfinder#43]
It would appear the nuspec file used to create the packages is missing from the NuGet release here: https://www.nuget.org/packages/Sitecore.Pathfinder/0.6.7-alpha

As a result, packages are not created.

**Comment by JakobChristensen** [comment]
That is odd. If I download and open the file from Nuget.org, it contains the right Sitecore.nuspec file.

I wonder if the NuGet Manager does not install .nuspec files.

**Comment by JakobChristensen** [comment]
I just tried to install the package in Visual Studio and the .nuspec file is there.

So I cannot reproduce the issue.
