### ISSUE TITLE
Image is not uploaded correctly

### ISSUE THREAD

**Issue by sitecorian** [JakobChristensen/Sitecore.Pathfinder#56]
Reproducible on 8.2 initial release.

To repro, have the following HelloWorld item file referencing an image and the image under /media library folder:

``` javascript
{
    "Item": {
        "Template": "/sitecore/templates/Sample/HelloWorld",
        "Template.CreateFromFields": true,
        "Template.Icon": "Applications/16x16/about.png",
        "Fields": {
            "Title": {
                "Value": "Pathfinder"
            },
            "Text": {
                "Value": "Welcome to Sitecore Pathfinder333"
            },
            "Image": {
                "Value": "/sitecore/media library/lighthouse",
                "Field.Type": "Image"
            }
        }
    }
}
```

Run scc.
Notice the following error in the console:

`scc.cmd(0,0): information SCC4008: Installing packages...
items\master\sitecore\media library\Lighthouse.jpg(0,0): error SCC5005: Media it
em created with wrong ID: {C3214297-CF9E-421C-B1D8-70AB5977CE00} != {9E6F63EF-C3
11-0103-F334-EAF8D8B14BBB}
items\master\sitecore\content\Home\HelloWorld.item.json(14,26,14,62): error SCC5`

As a result, the media library has both the media folder and media with the same name:
![2016-10-12_11-48-51](https://cloud.githubusercontent.com/assets/900910/19323566/55f34dd8-9072-11e6-99d1-046c5168b7b1.png)

The error above is happening because the media upload doesn't overwrite the media folder with the same name, so the ID validation fails.

**Comment by JakobChristensen** [comment]
Out of scope.
