### ISSUE TITLE
Reliable source of a Pathfinder

### ISSUE THREAD

**Issue by vonamord** [JakobChristensen/Sitecore.Pathfinder#60]
Hello,

Sadly to admit, but I wasn't able to use Pathfinder. I've tried to build it with gulp locally using last sources from github but in the end I was not able to find scc.cmd in .build\dist directory. So, I searched for a package on npm and nuget but these feeds has too old versions. So, the last hope was AppVeyor but still no luck because build process doesn't create any packages. For example here is a messages from successful build 0.9.397:
> Collecting artifacts...
> No artifacts found matching 'build\Sitecore.Pathfinder.zip' path
> No artifacts found matching 'build\Sitecore.Pathfinder.{version}.nupkg' path
> No artifacts found matching 'build\npm\sitecore-pathfinder-0.8.0-alpha.tgz' path``

I would like to ask for any help :) 
Thanks!

**Comment by JakobChristensen** [comment]
Hi 

Sorry, Pathfinder is very much work in progress, and is not intended for other than academic use.

Did you follow the setting up guide: https://github.com/JakobChristensen/Sitecore.Pathfinder/blob/master/docs/walkthroughs/SettingUp/README.md

**Comment by JakobChristensen** [comment]
Ahh - sorry, I can it is a AppVeyor issue...

**Comment by vonamord** [comment]
Unfortunately, I was following this guide https://github.com/JakobChristensen/Sitecore.Pathfinder/blob/master/docs/GettingStarted.md.

Okay, I see. Then I will not rely on any external tools and proceed with ./bin/netcoreapp1.1

I've noticed that it's not possible to run "scc init-habitat" because of lack of a habitat zip file 

Do you have any roadmap of release? Will Pathfinder be suitable to use along with Helix architecture? I really like this tool and am looking forward to use it as a next level of Sitecore delopment

**Comment by JakobChristensen** [comment]
AppVeyor issues should be resolved now.

Regarding Habitat: Habitat is evolving and synchronizing with Habitat requires some work. As Pathfinder was being reenvisioned, I removed a support for Habitat.
