### ISSUE TITLE
Icon attribute ignored on YAML templates

### ISSUE THREAD

**Issue by adeneys** [JakobChristensen/Sitecore.Pathfinder#64]
I've attempted to add the `Icon` attribute to a template defined in YAML, but when my package is built, the icon is not set for the template.

Following is a sample yaml file showing this issue:

    - Template: MyTemplate
        BaseTemplates: /sitecore/templates/sample/Sample Item
        Icon: Office/32x32/document_text.png
        - Section: Content
            - Field: Subtitle
                Type: Single-Line Text
                Sharing: Versioned

**Comment by JakobChristensen** [comment]
Fixed.
