### ISSUE TITLE
scc.exe should ensure correct server components version.

### ISSUE THREAD

**Issue by adeneys** [JakobChristensen/Sitecore.Pathfinder#8]
When scc.exe communicates with the Sitecore server it should verify the version of the server Pathfinder components. I was having issues with extensions not working on the server and eventually worked out that the Pathfinder DLLs in my bin folder where old, from a previous version of Sitecore.

If the server files are not the same version as the scc.exe running we could either redeploy silently, or ask the user if they wish to redeploy the server components.

**Comment by JakobChristensen** [comment]
Emils pull request fixed bad references, and I have fixed an issue in the server components deploy'er, so it should work now.

The BeforeBuild class checks for version, size and last write date of the assemblies and any changed assembly is copied to the server.

I think the issue is closed.
